### ISSUE TITLE
There are somthing wrong with The code you uploaded (eqg-race-unified.tar.gz) 

### ISSUE THREAD

**Issue by Congregalis** [jemmryx/EQG-RACE#3]
It is just **134** bytes.
When I tryied to extract files from this package, The error happened.
Love your idea in Education Question Generation.
I'd appreciate it if you could fix it soon.

**Comment by jemmryx** [comment]
> It is just **134** bytes.
> When I tryied to extract files from this package, The error happened.
> Love your idea in Education Question Generation.
> I'd appreciate it if you could fix it soon.

thanks! The original gz file has been deleted due to its large size ...... I uploaded a flattened version. Hope useful for you.

**Comment by Congregalis** [comment]
Thank you so much.
